## Import Package

In [2]:
import numpy as np
import pandas as pd
import os

# import seaborn as sns
import matplotlib.pyplot as plt
import torch
import torch.nn as nn
from torch.utils.data import DataLoader, Dataset

In [3]:
# from google.colab import drive

# drive.mount('/content/gdrive')

## Load Data

In [4]:
# df = pd.read_csv('/content/gdrive/My Drive/Capstone/d.Shuo/filtered_data.csv')

In [5]:
os.getcwd()

'/home/sagemaker-user/capstone-2024-summer/src/shuo'

In [6]:
!pwd

/home/sagemaker-user/capstone-2024-summer/src/shuo


In [7]:
df = pd.read_csv("../../data/filtered_data.csv")

In [8]:
df

PERMNO        date     CUSIP                  COMNAM TICKER  \
0         10026  2023-01-03  46603210  J & J SNACK FOODS CORP   JJSF   
1         10026  2023-01-04  46603210  J & J SNACK FOODS CORP   JJSF   
2         10026  2023-01-05  46603210  J & J SNACK FOODS CORP   JJSF   
3         10026  2023-01-06  46603210  J & J SNACK FOODS CORP   JJSF   
4         10026  2023-01-09  46603210  J & J SNACK FOODS CORP   JJSF   
...         ...         ...       ...                     ...    ...   
2197350   93436  2023-12-22  88160R10               TESLA INC   TSLA   
2197351   93436  2023-12-26  88160R10               TESLA INC   TSLA   
2197352   93436  2023-12-27  88160R10               TESLA INC   TSLA   
2197353   93436  2023-12-28  88160R10               TESLA INC   TSLA   
2197354   93436  2023-12-29  88160R10               TESLA INC   TSLA   

            NAICS PRIMEXCH       RET TRDSTAT  
0        311930.0        Q  0.011823       A  
1        311930.0        Q -0.001716       A  
2        311930.0        Q -0.010713       A  
3        311930.0        Q  0.020321       A  
4        311930.0        Q -0.019851       A  
...           ...      ...       ...     ...  
2197350  336110.0        Q -0.007701       A  
2197351  336110.0        Q  0.016116       A  
2197352  336110.0        Q  0.018822       A  
2197353  336110.0        Q -0.031594       A  
2197354  336110.0        Q -0.018564       A  

[2197355 rows x 9 columns]

In [9]:
df.dtypes

PERMNO        int64
date         object
CUSIP        object
COMNAM       object
TICKER       object
NAICS       float64
PRIMEXCH     object
RET         float64
TRDSTAT      object
dtype: object

## Feature Engineering

In [10]:
data_1 = df[["date", "TICKER", "RET"]]
data_1

date TICKER       RET
0        2023-01-03   JJSF  0.011823
1        2023-01-04   JJSF -0.001716
2        2023-01-05   JJSF -0.010713
3        2023-01-06   JJSF  0.020321
4        2023-01-09   JJSF -0.019851
...             ...    ...       ...
2197350  2023-12-22   TSLA -0.007701
2197351  2023-12-26   TSLA  0.016116
2197352  2023-12-27   TSLA  0.018822
2197353  2023-12-28   TSLA -0.031594
2197354  2023-12-29   TSLA -0.018564

[2197355 rows x 3 columns]

In [11]:
# Preprocess Data
data_1["log_return"] = np.log(data_1["RET"] + 1)
data_1

/tmp/ipykernel_2273/2781237886.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_1['log_return'] = np.log(data_1['RET'] + 1)


date TICKER       RET  log_return
0        2023-01-03   JJSF  0.011823    0.011754
1        2023-01-04   JJSF -0.001716   -0.001717
2        2023-01-05   JJSF -0.010713   -0.010771
3        2023-01-06   JJSF  0.020321    0.020117
4        2023-01-09   JJSF -0.019851   -0.020051
...             ...    ...       ...         ...
2197350  2023-12-22   TSLA -0.007701   -0.007731
2197351  2023-12-26   TSLA  0.016116    0.015988
2197352  2023-12-27   TSLA  0.018822    0.018647
2197353  2023-12-28   TSLA -0.031594   -0.032104
2197354  2023-12-29   TSLA -0.018564   -0.018738

[2197355 rows x 4 columns]

In [12]:
data_2 = data_1[["date", "TICKER", "log_return"]]
data_2

date TICKER  log_return
0        2023-01-03   JJSF    0.011754
1        2023-01-04   JJSF   -0.001717
2        2023-01-05   JJSF   -0.010771
3        2023-01-06   JJSF    0.020117
4        2023-01-09   JJSF   -0.020051
...             ...    ...         ...
2197350  2023-12-22   TSLA   -0.007731
2197351  2023-12-26   TSLA    0.015988
2197352  2023-12-27   TSLA    0.018647
2197353  2023-12-28   TSLA   -0.032104
2197354  2023-12-29   TSLA   -0.018738

[2197355 rows x 3 columns]

In [13]:
# Data Split - Train, Valid, and Test

In [14]:
# data = data_2
# data

In [15]:
# # Split the data into training, validation, and test sets
# data_len = len(data)
# train_size = int(0.7 * data_len)
# valid_size = int(0.15 * data_len)
# test_size = data_len - train_size - valid_size

# train_data = data.iloc[:train_size]
# valid_data = data.iloc[train_size:train_size + valid_size]
# test_data = data.iloc[train_size + valid_size:]

In [16]:
# train_data

In [17]:
# valid_data

In [18]:
# test_data

## Model

In [19]:
data = data_2
data

date TICKER  log_return
0        2023-01-03   JJSF    0.011754
1        2023-01-04   JJSF   -0.001717
2        2023-01-05   JJSF   -0.010771
3        2023-01-06   JJSF    0.020117
4        2023-01-09   JJSF   -0.020051
...             ...    ...         ...
2197350  2023-12-22   TSLA   -0.007731
2197351  2023-12-26   TSLA    0.015988
2197352  2023-12-27   TSLA    0.018647
2197353  2023-12-28   TSLA   -0.032104
2197354  2023-12-29   TSLA   -0.018738

[2197355 rows x 3 columns]

In [20]:
data.groupby("TICKER")["date"].describe()

count unique         top freq
TICKER                              
A        250    250  2023-12-29    1
AA       250    250  2023-12-29    1
AAA      250    250  2023-12-29    1
AAAU     250    250  2023-12-29    1
AACG     250    250  2023-12-29    1
...      ...    ...         ...  ...
ZVRA     211    211  2023-12-29    1
ZVSA     250    250  2023-12-29    1
ZWS      250    250  2023-12-29    1
ZYME     250    250  2023-12-29    1
ZYXI     250    250  2023-12-29    1

[8894 rows x 4 columns]

In [28]:
data[data["TICKER"] == "ZVRA"]

date TICKER  log_return
304303  2023-03-01   ZVRA   -0.062132
304304  2023-03-02   ZVRA   -0.024098
304305  2023-03-03   ZVRA    0.011194
304306  2023-03-06   ZVRA   -0.007449
304307  2023-03-07   ZVRA   -0.216159
...            ...    ...         ...
304509  2023-12-22   ZVRA    0.014185
304510  2023-12-26   ZVRA   -0.004032
304511  2023-12-27   ZVRA    0.101718
304512  2023-12-28   ZVRA    0.039361
304513  2023-12-29   ZVRA    0.138999

[211 rows x 3 columns]

In [29]:
first_month_data = data_2[data_2["date"] < "2023-02-01"]
first_month_data.head(30)

date TICKER  log_return
0    2023-01-03   JJSF    0.011754
1    2023-01-04   JJSF   -0.001717
2    2023-01-05   JJSF   -0.010771
3    2023-01-06   JJSF    0.020117
4    2023-01-09   JJSF   -0.020051
5    2023-01-10   JJSF    0.001736
6    2023-01-11   JJSF    0.016675
7    2023-01-12   JJSF    0.000262
8    2023-01-13   JJSF    0.013424
9    2023-01-17   JJSF   -0.001750
10   2023-01-18   JJSF   -0.038401
11   2023-01-19   JJSF   -0.007576
12   2023-01-20   JJSF   -0.020856
13   2023-01-23   JJSF    0.002423
14   2023-01-24   JJSF    0.037664
15   2023-01-25   JJSF    0.011785
16   2023-01-26   JJSF   -0.009922
17   2023-01-27   JJSF   -0.005266
18   2023-01-30   JJSF   -0.003481
19   2023-01-31   JJSF   -0.039811
250  2023-01-03    ELA    0.000000
251  2023-01-04    ELA   -0.007634
252  2023-01-05    ELA    0.000000
253  2023-01-06    ELA    0.005731
254  2023-01-09    ELA    0.042877
255  2023-01-10    ELA    0.037605
256  2023-01-11    ELA   -0.015943
257  2023-01-12    ELA   -0.014389
258  2023-01-13    ELA    0.058064
259  2023-01-17    ELA   -0.020726

### Check and make sure no missing values

In [30]:
first_month_data.dtypes

date           object
TICKER         object
log_return    float64
dtype: object

In [31]:
first_month_data[first_month_data["log_return"].isnull() == 1]

Empty DataFrame
Columns: [date, TICKER, log_return]
Index: []

In [32]:
first_month_data[first_month_data["date"].isnull() == 1]

Empty DataFrame
Columns: [date, TICKER, log_return]
Index: []

In [33]:
first_month_data.isnull().sum()

date          0
TICKER        0
log_return    0
dtype: int64

In [34]:
len(first_month_data)

171105

### Build Model & Get Embedding

#### Model-1
1. The current model does not use positional encodings.
2. Need to add ordinal position for each return.
3. Need to have 1 modified transformer encoder layer without residual connections + (n-1) standard layers
4. Need to connect the output of the first transformer block to the embedding layer of the fi- nal encoder block

In [35]:
first_month_data[:100].head(30)

date TICKER  log_return
0    2023-01-03   JJSF    0.011754
1    2023-01-04   JJSF   -0.001717
2    2023-01-05   JJSF   -0.010771
3    2023-01-06   JJSF    0.020117
4    2023-01-09   JJSF   -0.020051
5    2023-01-10   JJSF    0.001736
6    2023-01-11   JJSF    0.016675
7    2023-01-12   JJSF    0.000262
8    2023-01-13   JJSF    0.013424
9    2023-01-17   JJSF   -0.001750
10   2023-01-18   JJSF   -0.038401
11   2023-01-19   JJSF   -0.007576
12   2023-01-20   JJSF   -0.020856
13   2023-01-23   JJSF    0.002423
14   2023-01-24   JJSF    0.037664
15   2023-01-25   JJSF    0.011785
16   2023-01-26   JJSF   -0.009922
17   2023-01-27   JJSF   -0.005266
18   2023-01-30   JJSF   -0.003481
19   2023-01-31   JJSF   -0.039811
250  2023-01-03    ELA    0.000000
251  2023-01-04    ELA   -0.007634
252  2023-01-05    ELA    0.000000
253  2023-01-06    ELA    0.005731
254  2023-01-09    ELA    0.042877
255  2023-01-10    ELA    0.037605
256  2023-01-11    ELA   -0.015943
257  2023-01-12    ELA   -0.014389
258  2023-01-13    ELA    0.058064
259  2023-01-17    ELA   -0.020726

In [36]:
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
import pandas as pd
import numpy as np


class FinancialDataset(Dataset):
    def __init__(self, data, window_size=7):
        self.data = data
        self.window_size = window_size
        self.data["log_return"] = pd.to_numeric(self.data["log_return"], errors="coerce")
        self.data = self.data.dropna()

        # Group by ticker
        self.groups = self.data.groupby("TICKER")
        self.sequences = []

        for name, group in self.groups:
            if len(group) > self.window_size:
                for i in range(len(group) - self.window_size):
                    X = group["log_return"].iloc[i : i + self.window_size].values
                    y = group["log_return"].iloc[i + self.window_size]
                    self.sequences.append((X, y, name))

    def __len__(self):
        return len(self.sequences)

    def __getitem__(self, idx):
        X, y, ticker = self.sequences[idx]
        return {
            "features": torch.tensor(X, dtype=torch.float),
            "target": torch.tensor(y, dtype=torch.float),
            "ticker": ticker,
        }


class TransformerModel(nn.Module):
    def __init__(self, input_dim, embed_dim, n_heads, ff_dim, n_layers):
        super(TransformerModel, self).__init__()
        self.embedding = nn.Linear(input_dim, embed_dim)
        encoder_layer = nn.TransformerEncoderLayer(d_model=embed_dim, nhead=n_heads, dim_feedforward=ff_dim)
        self.transformer = nn.TransformerEncoder(encoder_layer, num_layers=n_layers)
        self.fc = nn.Linear(embed_dim, 1)

    def forward(self, x):
        x = self.embedding(x)  # Apply embedding layer
        x = x.unsqueeze(1)  # Add a dimension for the transformer (batch_size, seq_len, embed_dim)
        x = self.transformer(x)  # Transformer expects input of shape (seq_len, batch_size, embed_dim)
        # return self.fc(x[-1])
        embedding = x[:, -1, :]  # Get the last output token
        x = self.fc(x[:, -1, :])  # Fully connected layer on the last output token
        return x.squeeze(-1), embedding  # Return the final output and the embeddings


# Prepare Data
dataset = FinancialDataset(first_month_data[:100])
dataloader = DataLoader(dataset, batch_size=64, shuffle=False)

# Initialize Model
model = TransformerModel(input_dim=7, embed_dim=64, n_heads=8, ff_dim=256, n_layers=4)

# Training Loop
optimizer = torch.optim.RAdam(model.parameters(), lr=0.001)
# criterion = nn.MSELoss()
criterion = nn.L1Loss()

for epoch in range(1):
    for batch in dataloader:
        optimizer.zero_grad()
        output = model(batch["features"])
        loss = criterion(output[0].squeeze(), batch["target"])
        loss.backward()
        optimizer.step()

print("Training Complete")

/tmp/ipykernel_3735/2271390889.py:11: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.data['log_return'] = pd.to_numeric(self.data['log_return'], errors='coerce')


Training Complete


/opt/conda/lib/python3.10/site-packages/torch/nn/modules/loss.py:101: UserWarning: Using a target size (torch.Size([1])) that is different to the input size (torch.Size([])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.l1_loss(input, target, reduction=self.reduction)


In [37]:
# Extract embeddings for each stock
stock_embeddings = {}
model.eval()
with torch.no_grad():
    for batch in dataloader:
        _, embeddings = model(batch["features"])
        for i, ticker in enumerate(batch["ticker"]):
            if ticker not in stock_embeddings:
                stock_embeddings[ticker] = []
            stock_embeddings[ticker].append(embeddings[i].cpu().numpy())

In [38]:
# Average the embeddings for each stock
for ticker in stock_embeddings:
    stock_embeddings[ticker] = np.mean(stock_embeddings[ticker], axis=0)

In [39]:
stock_embeddings

{'ADX': array([-4.0977871e-01,  1.4794284e+00,  1.7840753e-01,  1.5000379e+00,
         1.1686856e+00,  6.4179522e-01, -2.0972960e+00,  8.7928808e-01,
        -1.3030480e+00,  2.5037482e+00, -7.1477401e-01, -2.7416018e-01,
         8.1865919e-01,  1.1520478e+00,  1.1321710e+00, -1.6067270e+00,
         4.0069807e-01,  5.5149603e-01, -5.5537599e-01, -1.4500427e+00,
        -1.0367236e+00,  7.1252865e-01, -8.9105427e-01,  5.0566548e-01,
        -1.2874995e+00,  2.4954444e-01,  3.3208850e-01,  2.0333575e-01,
        -1.9139947e-01, -4.4730511e-02,  1.6353710e+00,  1.2727789e+00,
         6.9922581e-02,  6.4895940e-01,  2.0228028e-03,  1.6969812e+00,
         9.6653616e-01, -9.5513433e-01,  9.2111386e-02,  3.1174499e-01,
        -1.1838439e+00, -5.0600719e-01, -5.6471610e-01, -7.0907301e-01,
         8.1805691e-02, -1.2215208e+00, -3.4610525e-01,  1.2865220e-01,
         1.5832239e-01,  6.2590653e-01, -1.3275002e-01,  1.8152727e+00,
         9.6626407e-01, -9.9946243e-01, -1.0747997e+00,  

In [40]:
for batch in dataloader:
    print(batch)
    break

{'features': tensor([[-0.0021,  0.0055, -0.0159,  0.0227, -0.0027,  0.0075,  0.0094],
        [ 0.0055, -0.0159,  0.0227, -0.0027,  0.0075,  0.0094,  0.0087],
        [-0.0159,  0.0227, -0.0027,  0.0075,  0.0094,  0.0087,  0.0033],
        [ 0.0227, -0.0027,  0.0075,  0.0094,  0.0087,  0.0033,  0.0013],
        [-0.0027,  0.0075,  0.0094,  0.0087,  0.0033,  0.0013, -0.0160],
        [ 0.0075,  0.0094,  0.0087,  0.0033,  0.0013, -0.0160, -0.0074],
        [ 0.0094,  0.0087,  0.0033,  0.0013, -0.0160, -0.0074,  0.0208],
        [ 0.0087,  0.0033,  0.0013, -0.0160, -0.0074,  0.0208,  0.0086],
        [ 0.0033,  0.0013, -0.0160, -0.0074,  0.0208,  0.0086, -0.0020],
        [ 0.0013, -0.0160, -0.0074,  0.0208,  0.0086, -0.0020, -0.0007],
        [-0.0160, -0.0074,  0.0208,  0.0086, -0.0020, -0.0007,  0.0151],
        [-0.0074,  0.0208,  0.0086, -0.0020, -0.0007,  0.0151,  0.0058],
        [ 0.0208,  0.0086, -0.0020, -0.0007,  0.0151,  0.0058, -0.0078],
        [ 0.0000, -0.0076,  0.0000,  0

In [41]:
model(batch["features"])

(tensor([-0.7987, -0.8022, -0.8023, -0.8046, -0.8039, -0.8120, -0.8056, -0.7935,
         -0.8021, -0.8041, -0.8049, -0.7987, -0.8041, -0.7935, -0.8174, -0.8131,
         -0.7786, -0.8262, -0.7970, -0.8130, -0.7747, -0.8146, -0.7903, -0.8152,
         -0.8075, -0.8043, -0.7986, -0.7972, -0.8065, -0.7966, -0.8059, -0.8209,
         -0.7992, -0.8120, -0.7967, -0.7843, -0.8014, -0.8085, -0.8066, -0.8043,
         -0.8113, -0.8036, -0.7973, -0.8107, -0.8039, -0.8105, -0.7958, -0.7983,
         -0.8040, -0.7965, -0.8856, -0.7681, -0.8044, -0.8123, -0.7997, -0.8081,
         -0.7703, -0.8095, -0.8100, -0.8048, -0.7989, -0.8065, -0.8011, -0.8079],
        grad_fn=<SqueezeBackward1>),
 tensor([[-0.3999,  1.4836,  0.1774,  ..., -1.0434, -0.6981, -0.1768],
         [-0.4147,  1.4703,  0.1829,  ..., -1.0459, -0.6923, -0.1954],
         [-0.4024,  1.4846,  0.1727,  ..., -1.0371, -0.7160, -0.1846],
         ...,
         [-0.4206,  1.4832,  0.1845,  ..., -1.0547, -0.6862, -0.1981],
         [-0.418

In [42]:
dataset.sequences

[(array([-0.00206513,  0.00549786, -0.01588957,  0.02271994, -0.00272671,
          0.00748095,  0.0094403 ]),
  0.008687157147454595,
  'ADX'),
 (array([ 0.00549786, -0.01588957,  0.02271994, -0.00272671,  0.00748095,
          0.0094403 ,  0.00868716]),
  0.0033214777803933435,
  'ADX'),
 (array([-0.01588957,  0.02271994, -0.00272671,  0.00748095,  0.0094403 ,
          0.00868716,  0.00332148]),
  0.0013251216383858657,
  'ADX'),
 (array([ 0.02271994, -0.00272671,  0.00748095,  0.0094403 ,  0.00868716,
          0.00332148,  0.00132512]),
  -0.01602166415441571,
  'ADX'),
 (array([-0.00272671,  0.00748095,  0.0094403 ,  0.00868716,  0.00332148,
          0.00132512, -0.01602166]),
  -0.007429530741163067,
  'ADX'),
 (array([ 0.00748095,  0.0094403 ,  0.00868716,  0.00332148,  0.00132512,
         -0.01602166, -0.00742953]),
  0.02079918938671432,
  'ADX'),
 (array([ 0.0094403 ,  0.00868716,  0.00332148,  0.00132512, -0.01602166,
         -0.00742953,  0.02079919]),
  0.0085949573037

#### Model-2
add ordinal position for each return

In [43]:
data

date TICKER  log_return
0        2023-01-03   JJSF    0.011754
1        2023-01-04   JJSF   -0.001717
2        2023-01-05   JJSF   -0.010771
3        2023-01-06   JJSF    0.020117
4        2023-01-09   JJSF   -0.020051
...             ...    ...         ...
2197350  2023-12-22   TSLA   -0.007731
2197351  2023-12-26   TSLA    0.015988
2197352  2023-12-27   TSLA    0.018647
2197353  2023-12-28   TSLA   -0.032104
2197354  2023-12-29   TSLA   -0.018738

[2197355 rows x 3 columns]

In [44]:
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
import pandas as pd
import numpy as np


class FinancialDataset(Dataset):
    def __init__(self, data, window_size=7):
        self.data = data
        self.window_size = window_size
        self.data["log_return"] = pd.to_numeric(self.data["log_return"], errors="coerce")
        self.data = self.data.dropna()

        # Group by ticker
        self.groups = self.data.groupby("TICKER")
        self.sequences = []

        for name, group in self.groups:
            j = self.window_size
            if len(group) > self.window_size:
                for i in range(len(group) - self.window_size):
                    X = group["log_return"].iloc[i : i + self.window_size].values
                    X = np.append(X, j)
                    j += 1

                    # print(X)
                    # t = np.arange(1, self.window_size + 1)  # Relative positions
                    # X = np.column_stack((X, t))  # Concatenate returns with positions

                    y = group["log_return"].iloc[i + self.window_size]
                    self.sequences.append((X, y, name))

    def __len__(self):
        return len(self.sequences)

    def __getitem__(self, idx):
        X, y, ticker = self.sequences[idx]
        return {
            "features": torch.tensor(X, dtype=torch.float),
            "target": torch.tensor(y, dtype=torch.float),
            "ticker": ticker,
        }


class TransformerModel(nn.Module):
    def __init__(self, input_dim, embed_dim, n_heads, ff_dim, n_layers):
        super(TransformerModel, self).__init__()
        self.embedding = nn.Linear(input_dim, embed_dim)
        encoder_layer = nn.TransformerEncoderLayer(d_model=embed_dim, nhead=n_heads, dim_feedforward=ff_dim)
        self.transformer = nn.TransformerEncoder(encoder_layer, num_layers=n_layers)
        self.fc = nn.Linear(embed_dim, 1)

    def forward(self, x):
        x = self.embedding(x)  # Apply embedding layer
        x = x.unsqueeze(1)  # Add a dimension for the transformer (batch_size, seq_len, embed_dim)
        x = self.transformer(x)  # Transformer expects input of shape (seq_len, batch_size, embed_dim)
        embedding = x[:, -1, :]  # Get the last output token
        x = self.fc(embedding)  # Fully connected layer on the last output token
        return x.squeeze(-1), embedding  # Return the final output and the embeddings


# Prepare Data
dataset = FinancialDataset(first_month_data[:100])
dataloader = DataLoader(dataset, batch_size=64, shuffle=False)

# Initialize Model
model = TransformerModel(input_dim=8, embed_dim=64, n_heads=8, ff_dim=256, n_layers=4)


# Training Loop
optimizer = torch.optim.RAdam(model.parameters(), lr=0.001)
criterion = nn.L1Loss()

for epoch in range(1):
    for batch in dataloader:
        optimizer.zero_grad()
        output, _ = model(batch["features"])
        loss = criterion(output, batch["target"])
        # print(f'loss: {loss}')
        loss.backward()
        optimizer.step()

print("Training Complete")

Training Complete


/tmp/ipykernel_3735/2799965795.py:11: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.data['log_return'] = pd.to_numeric(self.data['log_return'], errors='coerce')


In [45]:
batch["features"]

tensor([[-1.8697e-03,  1.8183e-02,  0.0000e+00,  9.0059e-04, -8.1340e-03,
         -5.4599e-03,  3.6434e-03,  1.9000e+01]])

In [46]:
for batch in dataloader:
    print(batch)
    break

{'features': tensor([[-2.0651e-03,  5.4979e-03, -1.5890e-02,  2.2720e-02, -2.7267e-03,
          7.4809e-03,  9.4403e-03,  7.0000e+00],
        [ 5.4979e-03, -1.5890e-02,  2.2720e-02, -2.7267e-03,  7.4809e-03,
          9.4403e-03,  8.6872e-03,  8.0000e+00],
        [-1.5890e-02,  2.2720e-02, -2.7267e-03,  7.4809e-03,  9.4403e-03,
          8.6872e-03,  3.3215e-03,  9.0000e+00],
        [ 2.2720e-02, -2.7267e-03,  7.4809e-03,  9.4403e-03,  8.6872e-03,
          3.3215e-03,  1.3251e-03,  1.0000e+01],
        [-2.7267e-03,  7.4809e-03,  9.4403e-03,  8.6872e-03,  3.3215e-03,
          1.3251e-03, -1.6022e-02,  1.1000e+01],
        [ 7.4809e-03,  9.4403e-03,  8.6872e-03,  3.3215e-03,  1.3251e-03,
         -1.6022e-02, -7.4295e-03,  1.2000e+01],
        [ 9.4403e-03,  8.6872e-03,  3.3215e-03,  1.3251e-03, -1.6022e-02,
         -7.4295e-03,  2.0799e-02,  1.3000e+01],
        [ 8.6872e-03,  3.3215e-03,  1.3251e-03, -1.6022e-02, -7.4295e-03,
          2.0799e-02,  8.5950e-03,  1.4000e+01],
   

In [47]:
# Extract embeddings for each stock
stock_embeddings = {}
model.eval()
with torch.no_grad():
    for batch in dataloader:
        _, embeddings = model(batch["features"])
        for i, ticker in enumerate(batch["ticker"]):
            if ticker not in stock_embeddings:
                stock_embeddings[ticker] = []
            stock_embeddings[ticker].append(embeddings[i].cpu().numpy())

In [48]:
np.array(stock_embeddings["ADX"]).shape

(13, 64)

In [49]:
first_month_data[first_month_data["TICKER"] == "ADX"]

date TICKER  log_return
1000  2023-01-03    ADX   -0.002065
1001  2023-01-04    ADX    0.005498
1002  2023-01-05    ADX   -0.015890
1003  2023-01-06    ADX    0.022720
1004  2023-01-09    ADX   -0.002727
1005  2023-01-10    ADX    0.007481
1006  2023-01-11    ADX    0.009440
1007  2023-01-12    ADX    0.008687
1008  2023-01-13    ADX    0.003321
1009  2023-01-17    ADX    0.001325
1010  2023-01-18    ADX   -0.016022
1011  2023-01-19    ADX   -0.007430
1012  2023-01-20    ADX    0.020799
1013  2023-01-23    ADX    0.008595
1014  2023-01-24    ADX   -0.001977
1015  2023-01-25    ADX   -0.000660
1016  2023-01-26    ADX    0.015068
1017  2023-01-27    ADX    0.005835
1018  2023-01-30    ADX   -0.007787
1019  2023-01-31    ADX    0.013588

In [50]:
# Average the embeddings for each stock
for ticker in stock_embeddings:
    stock_embeddings[ticker] = np.mean(stock_embeddings[ticker], axis=0)

In [51]:
stock_embeddings

{'ADX': array([-1.5693215 ,  0.7393916 , -0.75952446,  0.24287127,  0.43105495,
        -2.0098426 , -0.3524138 , -0.07705197,  0.17649871, -0.82372653,
        -1.5524913 ,  0.01574564,  0.41040185, -1.4154775 , -1.5905211 ,
        -2.0134366 ,  0.06378882, -1.4292376 , -0.8114132 , -1.3536326 ,
        -1.6023049 ,  1.3466197 ,  0.67438245,  1.3267403 ,  0.10103815,
         1.1108859 , -0.51997185, -0.16751502,  1.3460305 , -0.18993674,
         1.3611726 , -0.48505142, -0.40246725, -0.33503574, -1.6359662 ,
         0.2296785 ,  0.9340055 ,  2.0454152 ,  0.56274503,  1.3288411 ,
         1.0454892 ,  1.479027  , -0.00869759, -0.60328686, -0.5150685 ,
         0.5034568 , -0.7323853 ,  1.0065652 ,  0.5901592 , -0.3122196 ,
         0.73201466,  0.5433834 ,  0.14412059,  0.25566787, -0.36147025,
         2.1206114 ,  0.5148554 , -1.2760658 , -1.2155524 ,  0.87607443,
         0.94213474,  0.4792512 ,  0.05529883,  0.3855105 ], dtype=float32),
 'ELA': array([-1.5698621 ,  0.7405138 ,

#### Model-3  
customized transformer model

In [52]:
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
import pandas as pd
import numpy as np


class FinancialDataset(Dataset):
    def __init__(self, data, window_size=7):
        self.data = data
        self.window_size = window_size
        self.data["log_return"] = pd.to_numeric(self.data["log_return"], errors="coerce")
        self.data = self.data.dropna()

        # Group by ticker
        self.groups = self.data.groupby("TICKER")
        self.sequences = []

        for name, group in self.groups:
            j = self.window_size
            if len(group) > self.window_size:
                for i in range(len(group) - self.window_size):
                    X = group["log_return"].iloc[i : i + self.window_size].values
                    X = np.append(X, j)
                    j += 1

                    # print(X)
                    # t = np.arange(1, self.window_size + 1)  # Relative positions
                    # X = np.column_stack((X, t))  # Concatenate returns with positions

                    y = group["log_return"].iloc[i + self.window_size]
                    self.sequences.append((X, y, name))

    def __len__(self):
        return len(self.sequences)

    def __getitem__(self, idx):
        X, y, ticker = self.sequences[idx]
        return {
            "features": torch.tensor(X, dtype=torch.float),
            "target": torch.tensor(y, dtype=torch.float),
            "ticker": ticker,
        }


class TransformerModel(nn.Module):
    def __init__(self, input_dim, embed_dim, n_heads, ff_dim, n_layers):
        super(TransformerModel, self).__init__()
        self.embedding = nn.Linear(input_dim, embed_dim)
        encoder_layer = nn.TransformerEncoderLayer(d_model=embed_dim, nhead=n_heads, dim_feedforward=ff_dim)
        self.transformer1 = nn.TransformerEncoder(encoder_layer, num_layers=1)
        self.transformer2 = nn.TransformerEncoder(encoder_layer, num_layers=n_layers - 1)
        self.fc = nn.Linear(embed_dim, 1)

    def forward(self, x):
        x = self.embedding(x)  # Apply embedding layer
        x = x.unsqueeze(1)  # Add a dimension for the transformer (batch_size, seq_len, embed_dim)
        x1 = self.transformer1(x)  # Transformer expects input of shape (seq_len, batch_size, embed_dim)
        x2 = self.transformer2(x1)
        print(x2)
        embedding = x2[:, -1, :]  # Get the last output token
        x2 = self.fc(embedding)  # Fully connected layer on the last output token
        return x2.squeeze(-1), embedding  # Return the final output and the embeddings


# Prepare Data
dataset = FinancialDataset(first_month_data[:100])
dataloader = DataLoader(dataset, batch_size=64, shuffle=False)

# Initialize Model
model = TransformerModel(input_dim=8, embed_dim=64, n_heads=8, ff_dim=256, n_layers=4)


# Training Loop
optimizer = torch.optim.RAdam(model.parameters(), lr=0.001)
criterion = nn.L1Loss()

for epoch in range(1):
    for batch in dataloader:
        optimizer.zero_grad()
        output, _ = model(batch["features"])
        loss = criterion(output, batch["target"])
        # print(f'loss: {loss}')
        loss.backward()
        optimizer.step()

print("Training Complete")

tensor([[[-1.0205,  0.3921, -2.1875,  ..., -0.1326,  1.6290, -0.0188]],

        [[-1.5740,  0.3159, -2.2542,  ..., -0.1676,  1.6739,  0.1469]],

        [[-1.4329,  0.7343, -2.0170,  ..., -0.1700,  1.1782,  0.2251]],

        ...,

        [[-0.5899,  0.2753, -1.3605,  ..., -0.0638,  2.3149, -0.2101]],

        [[-0.8749,  0.5819, -1.6597,  ..., -0.0947,  2.1098, -0.3237]],

        [[-0.3667,  0.3423, -1.5161,  ...,  0.0068,  2.3132, -0.0355]]],
       grad_fn=<NativeLayerNormBackward0>)
tensor([[[-1.1356,  0.5978, -1.9611,  1.7115, -1.2320,  0.8944,  1.6332,
           1.4508, -1.3122, -0.1777,  0.6415,  1.0886, -0.9647,  0.3309,
           1.1053,  0.6896,  0.1552, -1.5701,  1.0047, -0.3343, -0.0600,
          -1.6041, -0.8242,  0.8059, -0.9545, -0.6658, -0.2572, -0.1256,
           1.1456,  1.1739, -1.3359,  0.1857,  0.6574, -1.4573, -2.0673,
           0.4832, -0.9365,  1.0854, -0.7773, -0.3432,  0.5446, -0.1355,
          -0.4938,  2.1090, -1.6365, -0.9929,  1.3641, -0.8064,  0.

/tmp/ipykernel_3735/1566622353.py:11: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.data['log_return'] = pd.to_numeric(self.data['log_return'], errors='coerce')
